rain:
    sources:
        github:
            labels:
                - spec
                - flow:tdd-development
                - feature
                - bug
astral:
    theme: custom
    names:
        - Mercator
        - Ptolemy
        - Strabo
        - Eratosthenes
        - Waldseemuller
        - Ortelius
        - Cresques
        - AlIdrisi
development:
    mode: github
